export * from './dtos/auth/login-alumno.dto';
export * from './dtos/auth/login-user.dto';
export * from './dtos/auth/register-alumno.dto';
export * from './dtos/grupo/create-grupo.dto';
export * from './dtos/grupo/update-grupo.dto';
export * from './dtos/jutificante/create-justificante-evidencia.dto.ts'
export * from './dtos/jutificante/create-justificante.dto';
export * from './dtos/user/create-alumno.dto';
export * from './dtos/user/create-tutor.dto';
export * from './dtos/user/update-alumno.dto';
export * from './dtos/user/update-tutor.dto'
export * from './errors/custom.error';